<?php
/**********************************
 *  Server Up Response
 *********************************/

function server_up_response_menu(){
    $items['server-up/respond'] = array(
        'title' => 'Server Up',
        'page callback' => 'server_up_response_respond',
        'page arguments'=>array(),
    );
    return $items;
}

function server_up_response_respond(){
    
    // do not allow caching
    drupal_page_is_cacheable(FALSE);
    
    return '<meta http-equiv="cache-control" content="max-age=0" />
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="expires" content="0" />
<meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
<meta http-equiv="pragma" content="no-cache" />
<p>'.date('U').'</p>';
}